import yaml
import os
from pathlib import Path

BASE = Path("/home/hartza123zazaza/phase_c")

# =====================
# database_spec.yaml
# =====================

db_spec = {
    "project": {
        "name": "ai_clinic_platform",
        "version": "v6",
        "database": "postgresql",
        "extensions": ["uuid-ossp", "vector"]
    },
    "tables": [
        {"name": "partners", "columns": {"id": "uuid", "name": "varchar", "created_at": "timestamp"}},
        {"name": "partner_branding", "columns": {"id": "uuid", "partner_id": "uuid", "logo_url": "varchar"}},
        {"name": "partner_domains", "columns": {"id": "uuid", "partner_id": "uuid", "domain": "varchar"}},
        {"name": "tenants", "columns": {"id": "uuid", "partner_id": "uuid", "name": "varchar"}},
        {"name": "tenant_settings", "columns": {"id": "uuid", "tenant_id": "uuid", "settings": "jsonb"}},
        {"name": "clinics", "columns": {"id": "uuid", "tenant_id": "uuid", "name": "varchar"}},
        {"name": "branches", "columns": {"id": "uuid", "clinic_id": "uuid", "name": "varchar"}},
        {"name": "users", "columns": {"id": "uuid", "tenant_id": "uuid", "email": "varchar"}},
        {"name": "roles", "columns": {"id": "uuid", "name": "varchar"}},
        {"name": "audit_logs", "columns": {"id": "uuid", "user_id": "uuid", "action": "varchar", "created_at": "timestamp"}},
        {"name": "white_label_brands", "columns": {"id": "uuid", "tenant_id": "uuid", "name": "varchar"}},
        {"name": "white_label_domains", "columns": {"id": "uuid", "brand_id": "uuid", "domain": "varchar"}},
        {"name": "white_label_assets", "columns": {"id": "uuid", "brand_id": "uuid", "asset_url": "varchar"}},
        {"name": "white_label_settings", "columns": {"id": "uuid", "brand_id": "uuid", "settings": "jsonb"}},
        {"name": "affiliates", "columns": {"id": "uuid", "name": "varchar", "email": "varchar"}},
        {"name": "affiliate_links", "columns": {"id": "uuid", "affiliate_id": "uuid", "code": "varchar"}},
        {"name": "affiliate_referrals", "columns": {"id": "uuid", "affiliate_id": "uuid", "customer_id": "uuid"}},
        {"name": "affiliate_clicks", "columns": {"id": "uuid", "link_id": "uuid", "clicked_at": "timestamp"}},
        {"name": "affiliate_conversions", "columns": {"id": "uuid", "referral_id": "uuid", "deal_id": "uuid"}},
        {"name": "affiliate_commissions", "columns": {"id": "uuid", "referral_id": "uuid", "amount": "numeric"}},
        {"name": "procedure_categories", "columns": {"id": "uuid", "name": "varchar"}},
        {"name": "procedures", "columns": {"id": "uuid", "category_id": "uuid", "name": "varchar"}},
        {"name": "procedure_pricing", "columns": {"id": "uuid", "procedure_id": "uuid", "clinic_id": "uuid", "price": "numeric"}},
        {"name": "procedure_benefits", "columns": {"id": "uuid", "procedure_id": "uuid", "benefit": "text"}},
        {"name": "procedure_risks", "columns": {"id": "uuid", "procedure_id": "uuid", "risk": "text"}},
        {"name": "procedure_images", "columns": {"id": "uuid", "procedure_id": "uuid", "image_url": "varchar"}},
        {"name": "procedure_videos", "columns": {"id": "uuid", "procedure_id": "uuid", "video_url": "varchar"}},
        {"name": "procedure_comparisons", "columns": {"id": "uuid", "procedure_a": "uuid", "procedure_b": "uuid", "comparison_data": "jsonb"}},
        {"name": "customers", "columns": {"id": "uuid", "clinic_id": "uuid", "name": "varchar"}},
        {"name": "customer_profiles", "columns": {"id": "uuid", "customer_id": "uuid", "data": "jsonb"}},
        {"name": "customer_preferences", "columns": {"id": "uuid", "customer_id": "uuid", "preferences": "jsonb"}},
        {"name": "customer_scores", "columns": {"id": "uuid", "customer_id": "uuid", "score": "numeric"}},
        {"name": "customer_tags", "columns": {"id": "uuid", "name": "varchar"}},
        {"name": "customer_tag_map", "columns": {"id": "uuid", "customer_id": "uuid", "tag_id": "uuid"}},
        {"name": "customer_history", "columns": {"id": "uuid", "customer_id": "uuid", "procedure_id": "uuid"}},
        {"name": "appointments", "columns": {"id": "uuid", "customer_id": "uuid", "scheduled_at": "timestamp"}},
        {"name": "appointment_logs", "columns": {"id": "uuid", "appointment_id": "uuid", "action": "varchar"}},
        {"name": "loyalty_points", "columns": {"id": "uuid", "customer_id": "uuid", "points": "integer"}},
        {"name": "conversations", "columns": {"id": "uuid", "customer_id": "uuid", "started_at": "timestamp"}},
        {"name": "messages", "columns": {"id": "uuid", "conversation_id": "uuid", "text": "text"}},
        {"name": "message_embeddings", "columns": {"id": "uuid", "message_id": "uuid", "embedding": "vector"}},
        {"name": "ai_recommendations", "columns": {"id": "uuid", "conversation_id": "uuid", "procedure_id": "uuid"}},
        {"name": "ai_decisions", "columns": {"id": "uuid", "conversation_id": "uuid", "decision_data": "jsonb"}},
        {"name": "conversation_feedback", "columns": {"id": "uuid", "conversation_id": "uuid", "rating": "integer"}},
        {"name": "leads", "columns": {"id": "uuid", "clinic_id": "uuid", "source": "varchar"}},
        {"name": "deals", "columns": {"id": "uuid", "lead_id": "uuid", "procedure_id": "uuid"}},
        {"name": "sales_pipeline", "columns": {"id": "uuid", "clinic_id": "uuid", "stage": "varchar"}},
        {"name": "sales_logs", "columns": {"id": "uuid", "deal_id": "uuid", "action": "varchar"}},
        {"name": "quotes", "columns": {"id": "uuid", "deal_id": "uuid", "price": "numeric"}},
        {"name": "campaigns", "columns": {"id": "uuid", "clinic_id": "uuid", "name": "varchar"}},
        {"name": "campaign_segments", "columns": {"id": "uuid", "campaign_id": "uuid", "rule": "jsonb"}},
        {"name": "campaign_messages", "columns": {"id": "uuid", "campaign_id": "uuid", "message": "text"}},
        {"name": "campaign_results", "columns": {"id": "uuid", "campaign_id": "uuid", "conversions": "integer"}},
        {"name": "ad_accounts", "columns": {"id": "uuid", "clinic_id": "uuid", "platform": "varchar"}},
        {"name": "ad_creatives", "columns": {"id": "uuid", "account_id": "uuid", "creative_url": "varchar"}},
        {"name": "ad_performance", "columns": {"id": "uuid", "creative_id": "uuid", "clicks": "integer"}},
        {"name": "invoices", "columns": {"id": "uuid", "clinic_id": "uuid", "total": "numeric"}},
        {"name": "payments", "columns": {"id": "uuid", "invoice_id": "uuid", "amount": "numeric"}},
        {"name": "subscriptions", "columns": {"id": "uuid", "tenant_id": "uuid", "plan": "varchar"}},
        {"name": "subscription_logs", "columns": {"id": "uuid", "subscription_id": "uuid", "action": "varchar"}},
        {"name": "refunds", "columns": {"id": "uuid", "payment_id": "uuid", "amount": "numeric"}},
        {"name": "billing_events", "columns": {"id": "uuid", "tenant_id": "uuid", "event": "varchar"}},
        {"name": "token_usage", "columns": {"id": "uuid", "tenant_id": "uuid", "tokens": "integer"}},
        {"name": "token_limits", "columns": {"id": "uuid", "tenant_id": "uuid", "limit_value": "integer"}},
        {"name": "token_logs", "columns": {"id": "uuid", "usage_id": "uuid", "created_at": "timestamp"}},
        {"name": "analytics_events", "columns": {"id": "uuid", "event_type": "varchar", "event_data": "jsonb"}},
        {"name": "conversion_logs", "columns": {"id": "uuid", "deal_id": "uuid", "converted": "boolean"}},
        {"name": "revenue_metrics", "columns": {"id": "uuid", "clinic_id": "uuid", "revenue": "numeric"}},
        {"name": "ai_performance_metrics", "columns": {"id": "uuid", "model": "varchar", "accuracy": "numeric"}},
        {"name": "dashboard_metrics", "columns": {"id": "uuid", "metric": "varchar", "value": "numeric"}},
        {"name": "report_exports", "columns": {"id": "uuid", "user_id": "uuid", "file_url": "varchar"}},
        {"name": "ai_datasets", "columns": {"id": "uuid", "dataset_type": "varchar", "data": "jsonb"}},
        {"name": "ai_training_logs", "columns": {"id": "uuid", "dataset_id": "uuid", "result": "jsonb"}},
        {"name": "ai_feedback", "columns": {"id": "uuid", "conversation_id": "uuid", "score": "integer"}},
        {"name": "learning_events", "columns": {"id": "uuid", "event_type": "varchar", "data": "jsonb"}},
        {"name": "dataset_improvements", "columns": {"id": "uuid", "dataset_id": "uuid", "change_data": "jsonb"}},
        {"name": "integrations", "columns": {"id": "uuid", "clinic_id": "uuid", "type": "varchar"}},
        {"name": "integration_tokens", "columns": {"id": "uuid", "integration_id": "uuid", "token": "varchar"}},
        {"name": "integration_logs", "columns": {"id": "uuid", "integration_id": "uuid", "log": "text"}},
        {"name": "webhook_events", "columns": {"id": "uuid", "source": "varchar", "payload": "jsonb"}},
        {"name": "integration_messages", "columns": {"id": "uuid", "integration_id": "uuid", "message": "text"}},
        {"name": "dashboards", "columns": {"id": "uuid", "tenant_id": "uuid", "name": "varchar"}},
        {"name": "dashboard_widgets", "columns": {"id": "uuid", "dashboard_id": "uuid", "widget_type": "varchar"}},
        {"name": "dashboard_layouts", "columns": {"id": "uuid", "dashboard_id": "uuid", "layout": "jsonb"}},
        {"name": "dashboard_snapshots", "columns": {"id": "uuid", "dashboard_id": "uuid", "snapshot": "jsonb"}},
        {"name": "dashboard_permissions", "columns": {"id": "uuid", "dashboard_id": "uuid", "user_id": "uuid"}},
        {"name": "system_configs", "columns": {"id": "uuid", "key": "varchar", "value": "jsonb"}},
        {"name": "system_logs", "columns": {"id": "uuid", "level": "varchar", "message": "text", "created_at": "timestamp"}},
        {"name": "feature_flags", "columns": {"id": "uuid", "name": "varchar", "enabled": "boolean"}},
    ]
}

with open(BASE / "specs/database_spec.yaml", "w") as f:
    yaml.dump(db_spec, f, allow_unicode=True, sort_keys=False)
print("database_spec.yaml created:", len(db_spec["tables"]), "tables")

